apiVersion: v1
kind: Service
metadata:
  name: awesome-app
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 10010
    targetPort: 80
    nodePort: 30020
  selector:
    app: awesome-app
  # type: LoadBalancer
  # externalTrafficPolicy: local