apiVersion: v1
kind: Service
metadata:
  name: awesome-app
  namespace: development
spec:
  # type: NodePort
  ports:
  - port: 30020
    targetPort: 80
    # nodePort: 30020
  selector:
    app: awesome-app
  type: LoadBalancer
  # externalTrafficPolicy: local