apiVersion: v1
kind: ReplicationController
metadata:
  name: awesome-app
  namespace: development
  labels:
    name: awesome-app
spec:
  replicas: 1
  selector:
    app: awesome-app
  template:
    metadata:
      labels:
        app: awesome-app
    spec:
      containers:
      - name: awesome-app
        image: docker.io/roandocker/k8s_haody:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        command: 
          - nginx
        env:
        - name: MYSQL_SERVICE_HOST
          value: 'awesome-app-mysql'
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
