apiVersion: v1
kind: ReplicationController
metadata:
  name: member-platform
  namespace: dev
  labels:
    name: member-platform
spec:
  replicas: 2
  selector:
    app: member-platform
  template:
    metadata:
      labels:
        app: member-platform
    spec:
      containers:
      - name: member-platform
        image: farzer/platform-preview:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # command: ["/bin/sh"]
        # args: ["-c","cd root; git clone http://git.tech.nanhaicorp.com.cn/dd01-member/member-platform-console.git; cd member-platform-console;"]
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 256Mi
        #   requests:
        #     cpu: 100m
        #     memory: 256Mi
